##############################################################################
###                               Testing                                  ###
##############################################################################
# (R) [str] Type of your scheduling problem - this template is for the asp
sp_type: asp
# (R)   [string]  GP algorithm you want to use
algorithm: gp
# (R)   [string]  Path to the file with generated data that to be used for test
instances_file: asp/config_ASP_variants_tubes_test.pkl
# (R)   [string]  Test Environment: Should be the same the agent was trained on
environment: env_gp
# (O)   [string]  Name of the model you want to load for testing
saved_model_name: ASP_variants_tubes_gp_best_rule
# (R)   [int]     Seed for all pseudo random generators (random, numpy, torch)
seed: 2
# (R)   [string]  Set an individual description that you can identify this
# training run  more easily later on. This will be used in
# "weights and biases" as well
config_description: ASP_variants_tubes_gp_best_rule
# (O)   [string]  Set a directory from where you want to load the agent model
experiment_save_path: models

